name: Plan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
          terraform_wrapper: false

      - name: Set up Terragrunt
        uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: v0.31.4

      - name: Terraform check format
        run: terraform fmt --recursive --check --diff

      - name: Terragrunt plan all
        run: terragrunt run-all plan
        working-directory: ./live/sandbox
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
