name: DEV Plan

on:
  push:
    branches: [ reusable-plan, main, dev ]
  pull_request:
    branches: [ reusable-plan, dev, main ]

jobs:
  call-plan-workflow:
      uses: liatrio-cloud/github-workflows/.github/workflows/terragrunt-plan-azure.yml@terragrunt-plan
      with:
        workingDirectory: ./live/sandbox
      secrets:
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

