name: DEV Plan

on:
  push:
    branches: [ reusable-plan, main, dev ]
  pull_request:
    branches: [ reusable-plan, dev, main ]

jobs:
  call-plan-workflow:
      uses: liatrio-cloud/github-workflows/.github/workflows/terragrunt-plan.yml@terragrunt-plan
      with:
        working-directory: ./live/sandbox
      secrets:
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        TF_VAR_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

