name: Terragrunt Plan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-plan-workflow:
      uses: liatrio-cloud/github-workflows/.github/workflows/terragrunt-plan-azure.yml@main
      with:
        workingDirectory: ./live/sandbox
      secrets:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

