name: Terragrunt Plan

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
      uses: liatrio-cloud/github-workflows/.github/workflows/terragrunt-plan-azure.yml@misc_fixes
      with:
        workingDirectory: ./live/sandbox
      secrets:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

