name: Terragrunt Plan Azure

concurrency: azure

on:
  pull_request:
    branches:
      - main
    paths:
      - live/sandbox/azure/**
      - sources/azure/**
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/liatrio-enterprise/runner-images/terraform-1.0:v1.1.2
      options: --user root
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terragrunt plan
        working-directory: ./live/sandbox/azure
        run: |
          set -ox pipefail
          terragrunt validate
          terragrunt plan
          terragrunt plan -out tfplan.plan
          terragrunt show -no-color -json tfplan.plan > tfplan.json
        id: plan
        shell: bash
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: 3e16852e-8399-4c16-b246-16bf46bc3747
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_LOG: DEBUG

  pullRequestComment:
    name: Comment on Pull Request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - plan
    steps:
      - name: Pull Request Comment
        uses: liatrio/terraform-change-pr-commenter@main
        with:
          json-file: ./live/sandbox/azure/tfplan.json
