name: DEV Plan

on:
  push:
    branches: [ reusable-plan, main, dev ]
  pull_request:
    branches: [ reusable-plan, dev, main ]

jobs:
  call-plan-workflwo:
      uses: liatrio-cloud/github-workflows/terragrunt-plan/.github/workflows/terragrunt-plan.yml@terragrunt-plan
      with:
        working-directory: ./live/sandbox/azure
      secrets:
        ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        TF_VAR_ARM_CLIENT_ID: "${{ secrets.DEV_ARM_CLIENT_ID }}"
        TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        TF_VAR_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}